.jscsrc
.travis.yml
README.md
lib/filter-es-compiler.js
package.json
test/elastic-adapter-limits.js
test/elastic-adapter.spec.js
test/elastic-test-utils.js
test/optimization.spec.js

A few changes to update travis now that the repository is open.

get travis working

---

.travis.yml
lib/elastic.js
lib/insert.js
lib/query-common.js
lib/query.js
lib/read.js
lib/utils.js
lib/write.js
package.json
test/elastic-adapter-limits.js
test/elastic-adapter.spec.js
test/elastic-test-utils.js
test/optimization.spec.js

This specifies the prefix for the index names you want to
read from. The suffix is the day of the points in the index.
If you don't specify a prefix, assumes you want logstash-.
This default can be overwritten in each configured backend
by adding an index_prefix key.

Add read/write -index_prefix

---

.travis.yml
package.json
test/optimization.spec.js

This is needed for #37 to pass tests.

package.json: bump juttle peerDependency to ^0.2.0

---

package.json

Remove the duplicated `chai` entry.
Move `uuid` into devDependencies.

package.json: tidy up a couple things

---

README.md
lib/elastic.js
lib/insert.js
lib/query-common.js
lib/query.js
lib/read.js
lib/utils.js
lib/write.js
test/elastic-adapter.spec.js
test/elastic-test-utils.js

Resolves https://github.com/juttle/juttle-elastic-adapter/issues/31
@demmer

Read/write -type

---

lib/es-errors.js
test/elastic-adapter-limits.js

Addresses #51
I don't want to start hacking people's config on their behalf, so just surface an error message that explains the problem and suggests the solution.

Improve error message for window overflow

---

test/elastic-adapter.spec.js
test/elastic-test-utils.js

Add test covering object/array fields in points.
refs: https://github.com/juttle/juttle/issues/55

Nested fields test

---

.travis.yml
lib/elastic.js
lib/es-errors.js
lib/insert.js
lib/query-common.js
lib/query.js
lib/read.js
lib/utils.js
lib/write.js
test/elastic-adapter-limits.spec.js
test/elastic-adapter.spec.js
test/elastic-test-utils.js
test/live.spec.js
test/optimization.spec.js

Add batch size and concurrent-request limits
Fixes #63 
Branched off https://github.com/juttle/juttle-elastic-adapter/pull/58, which means it needs a version of Juttle with the new adapter API to be published before it'll work in Travis.

Pace writes

---

README.md
docs/logstash.md

resolves #26 
@davidvgalbraith how's this?

Documenting specifics of Logstash schema

---

lib/elastic.js
test/validate-config.spec.js

config: validate in validate_config and add tests

---

.gitignore
.istanbul.yml
.travis.yml
package.json

lets add coverage checking for the elastic-adapter

add coverage checking

---

lib/read.js
test/elastic-adapter.spec.js

fixes https://github.com/juttle/juttle-elastic-adapter/issues/79
@VladVega @demmer

read: require from or to

---

lib/filter-es-compiler.js
test/elastic-adapter.spec.js

fixes https://github.com/juttle/juttle-elastic-adapter/issues/82

filterESCompiler: ban regexes

---

test/apache-sample.json
test/optimization.spec.js

New optimization tests

---

test/elastic-adapter.spec.js
test/elastic-test-utils.js
test/index-intervals.spec.js

write error tests: check they don't write

---

test/live.spec.js

live.spec: test with filter

---

lib/read.js
test/elastic-adapter.spec.js

A few more tests for https://github.com/juttle/juttle-elastic-adapter/issues/88:
- we can't optimize a filter like on idField, so spurn such things.
- warn if index/type missing
- big point big but not too big
@dmehra @VladVega

Miscellaneous tests

---

lib/elastic.js
lib/insert.js
package.json
test/elastic-test-utils.js

Use aws-es2 module instead of git URL

---

.travis.yml
lib/aggregation.js
lib/elastic.js
lib/filter-es-compiler.js
lib/insert.js
lib/optimize.js
lib/query-common.js
lib/query.js
lib/read.js
lib/write.js
package.json
test/elastic-adapter.spec.js
test/elastic-test-utils.js
test/optimization.spec.js
test/write.spec.js

Stacked on top of #103.
Implements the 0.5 API contract exposed by https://github.com/juttle/juttle/pull/413 in the elastic adapter.

Adapter api module

---

lib/query.js
lib/read.js
package.json
test/index-intervals.spec.js

fixes https://github.com/juttle/juttle-elastic-adapter/issues/119

read: take * out of index with indexInterval

---

CHANGELOG.md

CHANGELOG: updates for 0.6.2

---

.travis.yml
lib/filter-es-compiler.js
package.json
test/elastic-adapter.spec.js
test/filters.spec.js
test/nested-objects.spec.js

upgrade to Juttle 7
