- .travis.yml
- package.json
- test/elastic-adapter-limits.js
- test/elastic-adapter.spec.js
- test/elastic-test-utils.js
- test/optimization.spec.js
Back in https://github.com/juttle/juttle-elastic-adapter/pull/21 I lamentably had to get rid of testing on Node 4 because the parallel requests to my Amazon instance read/deleted each other's data. But now that we have https://github.com/juttle/juttle-elastic-adapter/pull/22 we can write to a unique set of indices per test run, so we don't have to worry about that. As a bonus it got a lot DRYer.
> Test node 4

- lib/filter-es-compiler.js
- test/elastic-adapter.spec.js
The AST nodes MomentConstant and DurationConstant were renamed to
MomentLiteral and DurationLiteral, so update the filter compiler
accordingly.
I noticed this same problem in https://github.com/juttle/juttle-sql-adapter-common/pull/6.
Also there should really be a test for this but I'm not familiar enough with how the data is put into ES in the unit test framework.
@davidvgalbraith could you consider adding a test to ensure we do the right thing when moment / duration literals are in the filter expressions?
> filter-es-compiler: update to juttle 0.2.0 AST node types

- README.md
- lib/elastic.js
- lib/insert.js
- lib/query-common.js
- lib/query.js
- lib/read.js
- lib/utils.js
- lib/write.js
- package.json
- test/elastic-adapter.spec.js
- test/elastic-test-utils.js
- test/index-intervals.spec.js
resolves #25 
Now you can read and write from weekly, monthly, yearly,
or singular indices by specifying -index_interval in
read commands or configuration.
@demmer @VladVega @go-oleg @rlgomes @dmehra
> Support non-day index intervals

- lib/elastic.js
- lib/insert.js
- lib/query.js
- lib/read.js
- lib/utils.js
- lib/write.js
- test/elastic-adapter.spec.js
- test/elastic-test-utils.js
connects to #25 
Now the point that the adapter will use as a timestamp for documents in
ES is configurable by the time_field option. Juttle points still have
"time", this just determines the name of the field that the adapter will
put pt.time in when writing and put into pt.time when reading.
@demmer @VladVega @go-oleg @dmehra @rlgomes @henridf
> read/write -timeField

- lib/insert.js
- lib/write.js
- test/elastic-adapter.spec.js
-Allow nested objects
-Allow long fields
Add some extra error handling to validate bulk responses
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/33. 
> write: relax constraints

- README.md
- lib/elastic.js
- lib/insert.js
- lib/optimize.js
- lib/query.js
- lib/read.js
- lib/utils.js
- lib/write.js
- test/elastic-adapter.spec.js
With read elastic -idField, the _id field of each document in Elasticsearch
will be written into the value of the -idField option if specified.
With write elastic -idField, the value of each point's `idField` is used
as the _id of the corresponding document in Elasticsearch.
fixes https://github.com/juttle/juttle-elastic-adapter/issues/32
> read/write: -idField

- lib/write.js
The call is a noop (because `Write` is a sink).
See juttle/juttle#131.
> Eliminate useless `emit_eof` call in `Write`

- .travis.yml
- README.md
- lib/aggregation.js
- lib/optimize.js
- lib/query.js
- test/optimization.spec.js
If there are >1000 buckets, do a date histogram instead of
proceeding bucket-by-bucket.
fixes https://github.com/juttle/juttle-elastic-adapter/issues/48
> Bring back date histograms

- lib/es-errors.js
- lib/query-common.js
- test/elastic-adapter.spec.js
fixes https://github.com/juttle/juttle-elastic-adapter/issues/38
Also, the old code path for empty results used to catch index 404
errors from ES and return empty results in that case, but we use the
ignoreUnavailable query parameter so those 404s don't show up anymore.
> read: return empty aggregation result if no data

- .travis.yml
- package.json
Using >= 0.3.0, the format used by other adapters.
@davidvgalbraith @demmer
> Update to juttle 0.3.0 both in package.json and travis.

- lib/optimize.js
- lib/query.js
- lib/read.js
- test/elastic-adapter-limits.js
- test/optimization.spec.js
All the read-sorting logic is already there from Jut 1.0, we
just have to turn it on by passing {direction: 'desc'} to query.js
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/36
@VladVega @demmer
> optimize tail

- lib/optimize.js
- lib/query.js
- test/elastic-adapter-limits.js
If the tail limit exceeds the fetch size, then we don't get points
in the right order. Rather than add a bunch of complexity to keep
optimizing this edge case, let's just not optimize it.
@VladVega
> tail: don't optimize beyond fetch_size

- .travis.yml
- lib/aggregation.js
- lib/query.js
- lib/utils.js
- test/elastic-adapter.spec.js
using millis made Jut 1.0 fly, but it's an unnecessary complication
now that doesn't play well with toNative's newfound view that all
numbers are seconds
Now that a version of Juttle with the "numbers are seconds" idea has been pushed, the adapter is giving weird times. Let's get this in and knock that off.
@demmer @VladVega @dmehra
> query: use ISO times, not millis

- lib/query.js
If all the results come back in a single fetch, there's no need
to do an extra bridge.
> query: don't do an unnecessary bridge fetch

- lib/aggregation.js
- lib/insert.js
- lib/optimize.js
- lib/utils.js
- lib/write.js
- test/elastic-adapter.spec.js
- test/elastic-test-utils.js
The date histogram builder assumes that the time field is always 'time'.
That's not right. It should use the timeField parameter.
This defeated our tests because we always write points with a "time" field
as well as the timeField, so date histograms on the "time" field work
even though it's not the timeField. Let's drop the "time" field from points
with a timeField on write.
fixes https://github.com/juttle/juttle-elastic-adapter/issues/66
@demmer @VladVega @dmehra
> optimizer: build date histograms with timeField

- README.md
- lib/elastic.js
- test/elastic-adapter.spec.js
- test/elastic-test-utils.js
The current paradigm, {type: 'aws'}, conflicts with the -type option
to read/write, so we can't do that.
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/67
> Indicate AWS backends with {aws: true}

- README.md
- lib/insert.js
- lib/utils.js
- lib/write.js
- package.json
- test/elastic-adapter.spec.js
- test/write.spec.js
instead of making a sequential request for each call to write()
buffer until we get chunkSize and flush at that time
use the new ConcurrencyMaster to make sure the specified
concurrency is respected
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/77
> write: speed up small batches

- lib/elastic.js
- lib/filter-es-compiler.js
- lib/read.js
- test/elastic-adapter.spec.js
Check the ES mapping each read and use that knowledge to trigger a warning if a program uses an unknown `timeField` or filters on or reduces by an analyzed or unknown field. 
> read: warn on invalid options

- README.md
- lib/read.js
- test/elastic-adapter.spec.js
- test/nested-objects.spec.js
Also warn if you reduce by an object field. Most of the tests are skipped because of https://github.com/juttle/juttle/issues/320. I'll open this PR so I don't forget about it, but probably not ready for merge unless we want a bunch of skipped tests in there.
> Test and document nested objects

- lib/query-common.js
- lib/utils.js
- test/index-intervals.spec.js
also current_week_number draws different week boundaries from
JuttleMoment, so we need to use current_week_number when deciding
what indices to read from
@VladVega @dmehra
> intervals: test data with multiple intervals

- lib/elastic.js
- test/elastic-test-utils.js
The AWS client now has the same API as the official ES client for
the functions it supports, so we don't need these instanceof checks
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/96
@VladVega
> Use AWS client's .indices

- test/elastic-adapter-limits.spec.js
- test/elastic-adapter.spec.js
- test/live.spec.js
- test/write.spec.js
We use type to refer to AWS/local as well as ES document type.
This is confusing, so use 'mode' for ES/local.
Finishes https://github.com/juttle/juttle-elastic-adapter/issues/88
@VladVega @dmehra
> tests: rename type -> mode

- lib/read.js
- test/nested-objects.spec.js
Currently we always warn if you do a nested property access
but instead we should deep-search the mapping for the property
fixes https://github.com/juttle/juttle-elastic-adapter/issues/111
@rlgomes @VladVega
> check_mapping: support nested fields

- lib/elastic.js
When warning about failing to get the mapping for a given index/type,
print a nicer message if the error is just that the index isn't there.
> quiet down the get mapping warning when there's no matching index

- lib/aggregation.js
- test/optimization.spec.js
When you do an optimized query against a non-existent index,
the Elastic response doesn't have an aggregations key, so we
crash when we call .hasOwnProperty on response.aggregations. We
already calculate the empty_result thing we're supposed to return
in this case, so let's actually use it.
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/120
> aggregations: fix missing index

- lib/read.js
- test/index-intervals.spec.js
Currently we check the mapping for this.index, which isn't
an actual index if we're using an indexInterval, only a prefix.
Let's check the mapping for the actual indices we're querying.
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/124
> read: use right indices in _check_options_vs_mapping

- lib/optimize.js
- lib/query.js
- lib/read.js
- lib/utils.js
- test/elastic-adapter-limits.spec.js
- test/optimization.spec.js
`read elastic` uses the same logic for `limit` as it does for `head` and
`tail`, so across any number of fetches it won't return more than a
total of `limit` points. This is not the right way to enforce `limit`,
which only applies to each individual call to the `read()` function.
The right way to enforce `limit` is to make it an upper bound on 
`fetch_size`, since each call to `read()` performs one fetch.
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/115
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/116
@VladVega @demmer
> read: don't apply limit globally

- README.md
@davidvgalbraith @mstemm linking from the adapter readme to its usage example, for better discovery of our helpful demo.
> Adding a link to demo examples

- lib/read.js
- test/elastic-test-utils.js
- test/logstash-mapping.json
- test/logstash-mapping.spec.js
When Logstash stores points, it creates a mapping where the .raw
is in the .fields. Currently, our mapping only looks in .properties.
Let's look in .fields too.
Also, let's ignore `_default_` which isn't a real type.
Fixes https://github.com/juttle/juttle-elastic-adapter/issues/126
@VladVega @demmer
> check_mapping: consider .fields

- lib/query.js
- test/optimization.spec.js
If reduce by has a missing field, we take the field out of the aggregation.
But if it's reduce by -every, we need to put it back for future batches.
Fixes #129 
Rework of #130
> read: restore aggregations

- lib/read.js
The change in Juttle 0.7.1 to wrap all vanilla JS errors coming from read in an internal error changed the test expectations since the error messages now included "internal error".
Instead catch the errors in the adapter itself and wrap them in a proper runtime error with an adapter-specific error code.
> read: wrap runtime errors in a juttle error
